import type { Permission } from "./permissions";
import { PERMISSIONS } from "./permissions";

const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  ADMIN: Object.values(PERMISSIONS),
  SUPREME: [
    PERMISSIONS.MAIL_READ,
    PERMISSIONS.MAIL_WRITE,
    PERMISSIONS.MAIL_DELETE,
    PERMISSIONS.MAIL_SEND,
    PERMISSIONS.ADMIN_USERS_READ,
    PERMISSIONS.ADMIN_USERS_WRITE,
    PERMISSIONS.ADMIN_DOMAINS_READ,
    PERMISSIONS.ADMIN_DOMAINS_WRITE,
    PERMISSIONS.ADMIN_QUEUE_READ,
    PERMISSIONS.ADMIN_QUEUE_MANAGE,
    PERMISSIONS.ADMIN_MONITORING,
    PERMISSIONS.ADMIN_ROLES,
    PERMISSIONS.ADMIN_QUOTAS,
    PERMISSIONS.ADMIN_DKIM,
    PERMISSIONS.ADMIN_SPAM,
    PERMISSIONS.ADMIN_NETWORK,
    PERMISSIONS.ADMIN_STORAGE,
    PERMISSIONS.SYSTEM_SETTINGS,
    PERMISSIONS.SYSTEM_ANALYTICS,
  ],
  ELITE: [
    PERMISSIONS.MAIL_READ,
    PERMISSIONS.MAIL_WRITE,
    PERMISSIONS.MAIL_DELETE,
    PERMISSIONS.MAIL_SEND,
    PERMISSIONS.ADMIN_MONITORING,
    PERMISSIONS.SYSTEM_ANALYTICS,
  ],
  BASIC: [
    PERMISSIONS.MAIL_READ,
    PERMISSIONS.MAIL_WRITE,
    PERMISSIONS.MAIL_DELETE,
    PERMISSIONS.MAIL_SEND,
  ],
  USER: [PERMISSIONS.MAIL_READ, PERMISSIONS.MAIL_SEND],
  GUEST: [PERMISSIONS.MAIL_READ],
};

export function mapRoleToPermissions(roles: string[]): Permission[] {
  const perms = new Set<Permission>();
  for (const role of roles) {
    const mapped = ROLE_PERMISSIONS[role.toUpperCase()];
    if (mapped) {
      for (const p of mapped) perms.add(p);
    }
  }
  return [...perms];
}
