import type { JmapEmail, JmapMailbox } from "@/features/mail/types";

export const mockMailboxes: JmapMailbox[] = [
  {
    id: "inbox-1",
    name: "Inbox",
    parentId: null,
    role: "inbox",
    sortOrder: 1,
    totalEmails: 1247,
    unreadEmails: 23,
    totalThreads: 892,
    unreadThreads: 18,
    myRights: {
      mayReadItems: true,
      mayAddItems: true,
      mayRemoveItems: true,
      mayModifyItems: true,
      mayCreateMailbox: false,
      mayDeleteMailbox: false,
      mayRenameMailbox: false,
      maySubmit: true,
    },
    isSubscribed: true,
  },
  {
    id: "drafts-1",
    name: "Drafts",
    parentId: null,
    role: "drafts",
    sortOrder: 2,
    totalEmails: 8,
    unreadEmails: 0,
    totalThreads: 8,
    unreadThreads: 0,
    myRights: {
      mayReadItems: true,
      mayAddItems: true,
      mayRemoveItems: true,
      mayModifyItems: true,
      mayCreateMailbox: false,
      mayDeleteMailbox: false,
      mayRenameMailbox: false,
      maySubmit: true,
    },
    isSubscribed: true,
  },
  {
    id: "sent-1",
    name: "Sent",
    parentId: null,
    role: "sent",
    sortOrder: 3,
    totalEmails: 4521,
    unreadEmails: 0,
    totalThreads: 2340,
    unreadThreads: 0,
    myRights: {
      mayReadItems: true,
      mayAddItems: true,
      mayRemoveItems: true,
      mayModifyItems: true,
      mayCreateMailbox: false,
      mayDeleteMailbox: false,
      mayRenameMailbox: false,
      maySubmit: true,
    },
    isSubscribed: true,
  },
  {
    id: "archive-1",
    name: "Archive",
    parentId: null,
    role: "archive",
    sortOrder: 4,
    totalEmails: 18432,
    unreadEmails: 0,
    totalThreads: 12890,
    unreadThreads: 0,
    myRights: {
      mayReadItems: true,
      mayAddItems: true,
      mayRemoveItems: true,
      mayModifyItems: true,
      mayCreateMailbox: false,
      mayDeleteMailbox: false,
      mayRenameMailbox: false,
      maySubmit: true,
    },
    isSubscribed: true,
  },
  {
    id: "spam-1",
    name: "Spam",
    parentId: null,
    role: "spam",
    sortOrder: 5,
    totalEmails: 342,
    unreadEmails: 5,
    totalThreads: 342,
    unreadThreads: 5,
    myRights: {
      mayReadItems: true,
      mayAddItems: true,
      mayRemoveItems: true,
      mayModifyItems: true,
      mayCreateMailbox: false,
      mayDeleteMailbox: false,
      mayRenameMailbox: false,
      maySubmit: true,
    },
    isSubscribed: true,
  },
  {
    id: "trash-1",
    name: "Trash",
    parentId: null,
    role: "trash",
    sortOrder: 6,
    totalEmails: 89,
    unreadEmails: 0,
    totalThreads: 89,
    unreadThreads: 0,
    myRights: {
      mayReadItems: true,
      mayAddItems: true,
      mayRemoveItems: true,
      mayModifyItems: true,
      mayCreateMailbox: false,
      mayDeleteMailbox: false,
      mayRenameMailbox: false,
      maySubmit: true,
    },
    isSubscribed: true,
  },
  {
    id: "important-1",
    name: "Important",
    parentId: null,
    role: "important",
    sortOrder: 7,
    totalEmails: 67,
    unreadEmails: 3,
    totalThreads: 54,
    unreadThreads: 2,
    myRights: {
      mayReadItems: true,
      mayAddItems: true,
      mayRemoveItems: true,
      mayModifyItems: true,
      mayCreateMailbox: false,
      mayDeleteMailbox: false,
      mayRenameMailbox: false,
      maySubmit: true,
    },
    isSubscribed: true,
  },
  {
    id: "flagged-1",
    name: "Flagged",
    parentId: null,
    role: "flagged",
    sortOrder: 8,
    totalEmails: 12,
    unreadEmails: 1,
    totalThreads: 12,
    unreadThreads: 1,
    myRights: {
      mayReadItems: true,
      mayAddItems: true,
      mayRemoveItems: true,
      mayModifyItems: true,
      mayCreateMailbox: false,
      mayDeleteMailbox: false,
      mayRenameMailbox: false,
      maySubmit: true,
    },
    isSubscribed: true,
  },
];

export const mockEmails: JmapEmail[] = [
  {
    id: "e1",
    blobId: "b1",
    threadId: "t1",
    mailboxIds: { "inbox-1": true },
    keywords: { $seen: false, $flagged: true },
    receivedAt: "2026-07-11T09:30:00Z",
    size: 24500,
    subject: "Quarterly Infrastructure Review - Action Items",
    from: [{ name: "Sarah Chen", email: "sarah.chen@omnixys.com" }],
    to: [{ name: "You", email: "admin@omnixys.com" }],
    cc: [{ name: "DevOps Team", email: "devops@omnixys.com" }],
    date: "2026-07-11T09:30:00Z",
    messageId: "<qir-2026-07-11@omnixys.com>",
    textBody: [{ partId: "t1", type: "text/plain", size: 1200 }],
    htmlBody: [{ partId: "h1", type: "text/html", size: 3400 }],
    attachments: [{ partId: "a1", type: "application/pdf", size: 185000 }],
    bodyValues: {
      t1: {
        value:
          "Hi team,\n\nPlease review the attached quarterly infrastructure report. Key highlights:\n\n1. Server uptime improved to 99.97%\n2. Mail queue latency reduced by 23%\n3. Storage migration to MinIO S3 is 80% complete\n4. New DKIM key rotation policy implemented\n\nAction items:\n- Review the migration timeline for Q3\n- Update monitoring dashboards\n- Schedule security audit for August\n\nPlease share your feedback by EOD Friday.\n\nBest,\nSarah",
        isEncodingProblem: false,
        isTruncated: false,
      },
    },
    headers: [
      { name: "From", value: "Sarah Chen <sarah.chen@omnixys.com>" },
      { name: "To", value: "admin@omnixys.com" },
      {
        name: "Subject",
        value: "Quarterly Infrastructure Review - Action Items",
      },
      { name: "Date", value: "Fri, 11 Jul 2026 09:30:00 +0000" },
      { name: "Message-ID", value: "<qir-2026-07-11@omnixys.com>" },
    ],
    hasAttachment: true,
  },
  {
    id: "e2",
    blobId: "b2",
    threadId: "t2",
    mailboxIds: { "inbox-1": true },
    keywords: { $seen: false },
    receivedAt: "2026-07-11T08:15:00Z",
    size: 18200,
    subject: "Re: New Domain Setup - startup.co",
    from: [{ name: "Marcus Weber", email: "marcus@startup.co" }],
    to: [{ name: "You", email: "admin@omnixys.com" }],
    date: "2026-07-11T08:15:00Z",
    messageId: "<re-domain-setup@startup.co>",
    textBody: [{ partId: "t1", type: "text/plain", size: 890 }],
    htmlBody: [],
    attachments: [],
    bodyValues: {
      t1: {
        value:
          "Hi,\n\nThanks for setting up the domain. I've added the MX and DKIM records as you suggested:\n\nMX: mail.startup.co -> mx.omnixys.com (priority 10)\nDKIM: default._domainkey.startup.co\n\nCan you confirm the DNS propagation is complete?\n\nThanks,\nMarcus",
        isEncodingProblem: false,
        isTruncated: false,
      },
    },
    headers: [
      { name: "From", value: "Marcus Weber <marcus@startup.co>" },
      { name: "To", value: "admin@omnixys.com" },
      { name: "Subject", value: "Re: New Domain Setup - startup.co" },
    ],
    hasAttachment: false,
  },
  {
    id: "e3",
    blobId: "b3",
    threadId: "t3",
    mailboxIds: { "inbox-1": true },
    keywords: { $seen: true },
    receivedAt: "2026-07-11T07:00:00Z",
    size: 45000,
    subject: "[GitHub] Security Alert: Dependency vulnerability in axios@1.7.9",
    from: [{ name: "GitHub", email: "noreply@github.com" }],
    to: [{ name: "You", email: "admin@omnixys.com" }],
    date: "2026-07-11T07:00:00Z",
    messageId: "<gh-alert-2026-07-11@github.com>",
    textBody: [{ partId: "t1", type: "text/plain", size: 2100 }],
    htmlBody: [{ partId: "h1", type: "text/html", size: 4500 }],
    attachments: [],
    bodyValues: {
      t1: {
        value:
          "We found a potential security vulnerability in a dependency of omnixys/webmail.\n\nVulnerability: CVE-2026-1234\nPackage: axios@1.7.9\nSeverity: Medium\nDescription: Server-Side Request Forgery in follow-redirects\n\nAffected versions: >=1.7.9\nPatched version: 1.8.0\n\nRecommended action: Update axios to version 1.8.0 or later.\n\nView the full advisory at: https://github.com/omnixys/webmail/security/dependabot/1",
        isEncodingProblem: false,
        isTruncated: false,
      },
    },
    headers: [
      { name: "From", value: "GitHub <noreply@github.com>" },
      { name: "To", value: "admin@omnixys.com" },
      {
        name: "Subject",
        value:
          "[GitHub] Security Alert: Dependency vulnerability in axios@1.7.9",
      },
    ],
    hasAttachment: false,
  },
  {
    id: "e4",
    blobId: "b4",
    threadId: "t4",
    mailboxIds: { "inbox-1": true },
    keywords: { $seen: false },
    receivedAt: "2026-07-10T16:45:00Z",
    size: 8900,
    subject: "Sprint Planning - Next Steps",
    from: [{ name: "Lisa Park", email: "lisa.park@omnixys.com" }],
    to: [
      { name: "You", email: "admin@omnixys.com" },
      { name: "Engineering Team", email: "eng@omnixys.com" },
    ],
    date: "2026-07-10T16:45:00Z",
    messageId: "<sprint-14@omnixys.com>",
    textBody: [{ partId: "t1", type: "text/plain", size: 650 }],
    htmlBody: [],
    attachments: [],
    bodyValues: {
      t1: {
        value:
          "Hey everyone,\n\nSprint 14 planning is scheduled for Monday at 10am. Please review the backlog and come prepared with your estimates.\n\nKey priorities:\n- Complete JMAP submission API integration\n- Implement sieve rule management UI\n- Fix the attachment download timeout issue\n\nSee you Monday!\nLisa",
        isEncodingProblem: false,
        isTruncated: false,
      },
    },
    headers: [
      { name: "From", value: "Lisa Park <lisa.park@omnixys.com>" },
      { name: "Subject", value: "Sprint Planning - Next Steps" },
    ],
    hasAttachment: false,
  },
  {
    id: "e5",
    blobId: "b5",
    threadId: "t5",
    mailboxIds: { "inbox-1": true },
    keywords: { $seen: true, $flagged: true },
    receivedAt: "2026-07-10T14:20:00Z",
    size: 15600,
    subject: "Re: TLS Certificate Renewal Reminder",
    from: [{ name: "Let's Encrypt", email: "notifications@letsencrypt.org" }],
    to: [{ name: "You", email: "admin@omnixys.com" }],
    date: "2026-07-10T14:20:00Z",
    messageId: "<le-renewal-2026@letsencrypt.org>",
    textBody: [{ partId: "t1", type: "text/plain", size: 1100 }],
    htmlBody: [{ partId: "h1", type: "text/html", size: 2800 }],
    attachments: [],
    bodyValues: {
      t1: {
        value:
          "Your certificate for mail.omnixys.com will expire in 14 days.\n\nPlease renew it before July 24, 2026.\n\nCertificate details:\n- Domain: mail.omnixys.com\n- Issuer: Let's Encrypt\n- Expires: 2026-07-24T00:00:00Z\n- Serial: 04:AB:CD:EF:12:34\n\nAuto-renewal is enabled but may fail if DNS validation is not configured.",
        isEncodingProblem: false,
        isTruncated: false,
      },
    },
    headers: [
      { name: "From", value: "Let's Encrypt <notifications@letsencrypt.org>" },
      { name: "Subject", value: "Re: TLS Certificate Renewal Reminder" },
    ],
    hasAttachment: false,
  },
  {
    id: "e6",
    blobId: "b6",
    threadId: "t6",
    mailboxIds: { "inbox-1": true },
    keywords: { $seen: true },
    receivedAt: "2026-07-10T11:00:00Z",
    size: 32000,
    subject: "Weekly System Health Report",
    from: [{ name: "Omnixys Monitor", email: "monitor@omnixys.com" }],
    to: [{ name: "You", email: "admin@omnixys.com" }],
    date: "2026-07-10T11:00:00Z",
    messageId: "<health-w28@omnixys.com>",
    textBody: [{ partId: "t1", type: "text/plain", size: 3200 }],
    htmlBody: [{ partId: "h1", type: "text/html", size: 8900 }],
    attachments: [{ partId: "a1", type: "text/csv", size: 12000 }],
    bodyValues: {
      t1: {
        value:
          "Weekly Health Report - Week 28, 2026\n\n=== UPTIME ===\nSMTP: 99.99%\nJMAP: 99.98%\nIMAP: 99.97%\nSieve: 100.00%\n\n=== PERFORMANCE ===\nAvg delivery latency: 42ms (down 15%)\nAvg JMAP response time: 28ms (down 8%)\nPeak concurrent connections: 1,247\n\n=== STORAGE ===\nPostgreSQL: 1.2TB / 2.0TB (60%)\nMinIO S3: 890GB / 1.5TB (59%)\nMeilisearch: 310GB / 500GB (62%)\n\n=== QUEUE ===\nCurrent queue size: 23\nAvg queue wait time: 1.2s\nBounce rate: 0.4%\n\n=== SECURITY ===\nSpam blocked: 2,847 messages\nFailed login attempts: 12\nDKIM verification rate: 99.2%\n\nFull report attached as CSV.",
        isEncodingProblem: false,
        isTruncated: false,
      },
    },
    headers: [
      { name: "From", value: "Omnixys Monitor <monitor@omnixys.com>" },
      { name: "Subject", value: "Weekly System Health Report" },
    ],
    hasAttachment: true,
  },
  {
    id: "e7",
    blobId: "b7",
    threadId: "t7",
    mailboxIds: { "inbox-1": true },
    keywords: { $seen: false },
    receivedAt: "2026-07-10T09:30:00Z",
    size: 12000,
    subject: "Invitation: Team Offsite - August 15-17",
    from: [{ name: "HR Team", email: "hr@omnixys.com" }],
    to: [{ name: "All Employees", email: "all@omnixys.com" }],
    date: "2026-07-10T09:30:00Z",
    messageId: "<offsite-2026@omnixys.com>",
    textBody: [{ partId: "t1", type: "text/plain", size: 1800 }],
    htmlBody: [{ partId: "h1", type: "text/html", size: 4500 }],
    attachments: [{ partId: "a1", type: "application/pdf", size: 250000 }],
    bodyValues: {
      t1: {
        value:
          "Hi everyone!\n\nWe're excited to announce our Q3 team offsite!\n\nDates: August 15-17, 2026\nLocation: Lake Conference Center, Lake Zurich\n\nAgenda:\n- Day 1: Strategy & Planning\n- Day 2: Team Building & Workshops\n- Day 3: Hackathon & Wrap-up\n\nPlease RSVP by July 25 and indicate any dietary requirements.\n\nLooking forward to seeing everyone there!\nHR Team",
        isEncodingProblem: false,
        isTruncated: false,
      },
    },
    headers: [
      { name: "From", value: "HR Team <hr@omnixys.com>" },
      { name: "Subject", value: "Invitation: Team Offsite - August 15-17" },
    ],
    hasAttachment: true,
  },
  {
    id: "e8",
    blobId: "b8",
    threadId: "t8",
    mailboxIds: { "inbox-1": true },
    keywords: { $seen: true },
    receivedAt: "2026-07-09T15:00:00Z",
    size: 6700,
    subject: "Re: Database Migration Plan",
    from: [{ name: "Alex Mueller", email: "alex.m@omnixys.com" }],
    to: [{ name: "You", email: "admin@omnixys.com" }],
    date: "2026-07-09T15:00:00Z",
    messageId: "<db-migrate@omnixys.com>",
    textBody: [{ partId: "t1", type: "text/plain", size: 980 }],
    htmlBody: [],
    attachments: [],
    bodyValues: {
      t1: {
        value:
          "Hey,\n\nI've reviewed the migration plan and it looks good. One suggestion:\n\nFor the PostgreSQL upgrade, we should run a dry-run migration on staging first. The data volume is significant (1.2TB) and we want to ensure the migration window is accurate.\n\nI've prepared a staging environment with a copy of production data. Can we schedule a test migration for next week?\n\nAlso, should we notify the on-call team about the maintenance window?\n\nCheers,\nAlex",
        isEncodingProblem: false,
        isTruncated: false,
      },
    },
    headers: [
      { name: "From", value: "Alex Mueller <alex.m@omnixys.com>" },
      { name: "Subject", value: "Re: Database Migration Plan" },
    ],
    hasAttachment: false,
  },
  {
    id: "e9",
    blobId: "b9",
    threadId: "t9",
    mailboxIds: { "inbox-1": true },
    keywords: { $seen: false },
    receivedAt: "2026-07-09T10:15:00Z",
    size: 28000,
    subject: "FW: Customer Escalation - Acme Corp Email Delivery Issues",
    from: [{ name: "Support Team", email: "support@omnixys.com" }],
    to: [{ name: "You", email: "admin@omnixys.com" }],
    date: "2026-07-09T10:15:00Z",
    messageId: "<escalation-acme@omnixys.com>",
    textBody: [{ partId: "t1", type: "text/plain", size: 2400 }],
    htmlBody: [],
    attachments: [],
    bodyValues: {
      t1: {
        value:
          "Escalation from Acme Corp:\n\nCustomer: Acme Corp (acme.io)\nIssue: Emails to external recipients bouncing with '550 5.7.1 Message rejected'\nAffected users: 12 out of 54\nStarted: July 8, 2026 16:00 UTC\nPriority: High\n\nInvestigation:\n- Checked queue: no backlog\n- Verified DKIM signing: OK\n- Checked SPF records: OK\n- Found issue: Their IP range 45.33.x.x is on a temporary blocklist\n\nAction taken:\n- Requested delisting from blocklist provider\n- Implemented temporary bypass in RBL checks\n- Monitoring delivery for affected users\n\nPlease review and advise on permanent solution.\n\nSupport Team",
        isEncodingProblem: false,
        isTruncated: false,
      },
    },
    headers: [
      { name: "From", value: "Support Team <support@omnixys.com>" },
      {
        name: "Subject",
        value: "FW: Customer Escalation - Acme Corp Email Delivery Issues",
      },
    ],
    hasAttachment: false,
  },
  {
    id: "e10",
    blobId: "b10",
    threadId: "t10",
    mailboxIds: { "inbox-1": true },
    keywords: { $seen: true },
    receivedAt: "2026-07-08T14:30:00Z",
    size: 5600,
    subject: "Welcome to Omnixys Mail!",
    from: [{ name: "Omnixys Team", email: "welcome@omnixys.com" }],
    to: [{ name: "You", email: "admin@omnixys.com" }],
    date: "2026-07-08T14:30:00Z",
    messageId: "<welcome-2026@omnixys.com>",
    textBody: [{ partId: "t1", type: "text/plain", size: 1200 }],
    htmlBody: [{ partId: "h1", type: "text/html", size: 3200 }],
    attachments: [],
    bodyValues: {
      t1: {
        value:
          "Welcome to Omnixys Mail!\n\nYour enterprise webmail platform is now set up and ready to use.\n\nQuick start:\n1. Access your mailbox at mail.omnixys.com\n2. Configure your email client using JMAP protocol\n3. Set up sieve rules for email filtering\n\nDocumentation: https://docs.omnixys.com\nSupport: support@omnixys.com\n\nBest regards,\nThe Omnixys Team",
        isEncodingProblem: false,
        isTruncated: false,
      },
    },
    headers: [
      { name: "From", value: "Omnixys Team <welcome@omnixys.com>" },
      { name: "Subject", value: "Welcome to Omnixys Mail!" },
    ],
    hasAttachment: false,
  },
];
