import type {
  StalwartAccount,
  StalwartAlias,
  StalwartDomain,
  StalwartGroup,
  StalwartQueuedMessage,
} from "@/features/admin/types";

export const mockAccounts: StalwartAccount[] = [
  {
    id: "u1",
    name: "admin@omnixys.com",
    description: "System Administrator",
    typ: "individual",
    role: "admin",
    disabled: false,
    isTenantAdmin: true,
  },
  {
    id: "u2",
    name: "sarah.chen@omnixys.com",
    description: "Engineering Lead",
    typ: "individual",
    role: "admin",
    disabled: false,
  },
  {
    id: "u3",
    name: "lisa.park@omnixys.com",
    description: "Product Manager",
    typ: "individual",
    role: "user",
    disabled: false,
  },
  {
    id: "u4",
    name: "alex.m@omnixys.com",
    description: "DevOps Engineer",
    typ: "individual",
    role: "user",
    disabled: false,
  },
  {
    id: "u5",
    name: "john.doe@omnixys.com",
    description: "Software Engineer",
    typ: "individual",
    role: "user",
    disabled: false,
  },
  {
    id: "u6",
    name: "marcus@startup.co",
    description: "CEO, Startup Co",
    typ: "individual",
    role: "user",
    disabled: false,
  },
  {
    id: "u7",
    name: "jane.smith@acme.io",
    description: "CTO, Acme Corp",
    typ: "individual",
    role: "user",
    disabled: false,
  },
  {
    id: "u8",
    name: "support@omnixys.com",
    description: "Support Team",
    typ: "group",
    role: "user",
    disabled: false,
  },
  {
    id: "u9",
    name: "devops@omnixys.com",
    description: "DevOps Team",
    typ: "group",
    role: "user",
    disabled: false,
  },
  {
    id: "u10",
    name: "old.user@mail.dev",
    description: "Former Employee",
    typ: "individual",
    role: "user",
    disabled: true,
  },
  {
    id: "u11",
    name: "new.hire@omnixys.com",
    description: "Junior Developer",
    typ: "individual",
    role: "user",
    disabled: false,
  },
  {
    id: "u12",
    name: "hr@omnixys.com",
    description: "HR Department",
    typ: "group",
    role: "user",
    disabled: false,
  },
  {
    id: "u13",
    name: "finance@omnixys.com",
    description: "Finance Team",
    typ: "group",
    role: "user",
    disabled: false,
  },
  {
    id: "u14",
    name: "ceo@omnixys.com",
    description: "Chief Executive Officer",
    typ: "individual",
    role: "admin",
    disabled: false,
  },
  {
    id: "u15",
    name: "contractor@external.com",
    description: "External Contractor",
    typ: "individual",
    role: "user",
    disabled: false,
  },
];

export const mockDomains: StalwartDomain[] = [
  {
    id: "d1",
    name: "omnixys.com",
    description: "Primary company domain",
    enabled: true,
    maxUsers: 200,
    plan: "Enterprise",
  },
  {
    id: "d2",
    name: "mail.dev",
    description: "Development & staging",
    enabled: true,
    maxUsers: 100,
    plan: "Professional",
  },
  {
    id: "d3",
    name: "acme.io",
    description: "Acme Corp tenant",
    enabled: true,
    maxUsers: 60,
    plan: "Professional",
  },
  {
    id: "d4",
    name: "startup.co",
    description: "Startup Co tenant",
    enabled: true,
    maxUsers: 50,
    plan: "Starter",
  },
  {
    id: "d5",
    name: "enterprise.de",
    description: "German enterprise client",
    enabled: true,
    maxUsers: 30,
    plan: "Enterprise",
  },
  {
    id: "d6",
    name: "old-domain.com",
    description: "Deprecated domain",
    enabled: false,
    maxUsers: 10,
    plan: "Starter",
  },
  {
    id: "d7",
    name: "test.local",
    description: "Internal testing",
    enabled: true,
    maxUsers: 5,
    plan: "Starter",
  },
];

export const mockAliases: StalwartAlias[] = [
  {
    id: "a1",
    name: "info",
    domain: "omnixys.com",
    addresses: ["admin@omnixys.com", "support@omnixys.com"],
    enabled: true,
  },
  {
    id: "a2",
    name: "support",
    domain: "omnixys.com",
    addresses: ["support@omnixys.com", "lisa.park@omnixys.com"],
    enabled: true,
  },
  {
    id: "a3",
    name: "sales",
    domain: "omnixys.com",
    addresses: ["admin@omnixys.com", "hr@omnixys.com"],
    enabled: true,
  },
  {
    id: "a4",
    name: "webmaster",
    domain: "omnixys.com",
    addresses: ["alex.m@omnixys.com"],
    enabled: true,
  },
  {
    id: "a5",
    name: "noreply",
    domain: "omnixys.com",
    addresses: ["system@omnixys.com"],
    enabled: true,
  },
  {
    id: "a6",
    name: "admin",
    domain: "startup.co",
    addresses: ["marcus@startup.co"],
    enabled: true,
  },
  {
    id: "a7",
    name: "contact",
    domain: "acme.io",
    addresses: ["jane.smith@acme.io", "jane.smith@acme.io"],
    enabled: true,
  },
  {
    id: "a8",
    name: "deprecated",
    domain: "old-domain.com",
    addresses: ["nobody@old-domain.com"],
    enabled: false,
  },
];

export const mockGroups: StalwartGroup[] = [
  {
    id: "g1",
    name: "Engineering",
    description: "All engineering staff",
    members: [
      "sarah.chen@omnixys.com",
      "alex.m@omnixys.com",
      "john.doe@omnixys.com",
    ],
  },
  {
    id: "g2",
    name: "DevOps",
    description: "DevOps and SRE team",
    members: ["alex.m@omnixys.com", "admin@omnixys.com"],
  },
  {
    id: "g3",
    name: "Management",
    description: "Company leadership",
    members: ["admin@omnixys.com", "ceo@omnixys.com", "sarah.chen@omnixys.com"],
  },
];

export const mockQueue: StalwartQueuedMessage[] = [
  {
    id: "q1",
    from: "system@omnixys.com",
    to: ["external@partner.com"],
    domain: "omnixys.com",
    size: 2450,
    created: "2026-07-11T10:00:00Z",
    status: "queued",
    priority: 0,
    retryCount: 0,
  },
  {
    id: "q2",
    from: "noreply@omnixys.com",
    to: ["user@acme.io"],
    domain: "omnixys.com",
    size: 1800,
    created: "2026-07-11T10:05:00Z",
    status: "queued",
    priority: 0,
    retryCount: 0,
  },
  {
    id: "q3",
    from: "marcus@startup.co",
    to: ["contact@external.com"],
    domain: "startup.co",
    size: 5600,
    created: "2026-07-11T10:10:00Z",
    status: "deferred",
    priority: 1,
    retryCount: 3,
  },
  {
    id: "q4",
    from: "admin@omnixys.com",
    to: ["bulk@list.com"],
    domain: "omnixys.com",
    size: 12400,
    created: "2026-07-11T10:15:00Z",
    status: "queued",
    priority: 0,
    retryCount: 0,
  },
  {
    id: "q5",
    from: "system@omnixys.com",
    to: ["bounce@invalid.test"],
    domain: "omnixys.com",
    size: 900,
    created: "2026-07-11T09:50:00Z",
    status: "failed",
    priority: 0,
    retryCount: 5,
  },
];
