import type { Notification } from "@/features/notifications/types";

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    type: "mail",
    title: "New email from Sarah Chen",
    message: "Quarterly Infrastructure Review - Action Items",
    read: false,
    timestamp: "2026-07-11T09:30:00Z",
    actionUrl: "/mail/inbox",
    priority: "high",
  },
  {
    id: "n2",
    type: "security",
    title: "New login detected",
    message: "Login from 192.168.1.42 (Chrome on macOS) at 09:15",
    read: false,
    timestamp: "2026-07-11T09:15:00Z",
    priority: "high",
  },
  {
    id: "n3",
    type: "system",
    title: "DKIM key rotated",
    message: "DKIM signing key for omnixys.com has been automatically rotated",
    read: false,
    timestamp: "2026-07-11T08:00:00Z",
    priority: "normal",
  },
  {
    id: "n4",
    type: "mail",
    title: "Mail queue backlog cleared",
    message: "47 messages delivered successfully after temporary congestion",
    read: true,
    timestamp: "2026-07-11T07:45:00Z",
    priority: "normal",
  },
  {
    id: "n5",
    type: "admin",
    title: "New domain added",
    message: "startup.co has been added and is pending DNS verification",
    read: true,
    timestamp: "2026-07-11T07:00:00Z",
    priority: "normal",
  },
  {
    id: "n6",
    type: "security",
    title: "TLS certificate renewed",
    message:
      "Certificate for mail.dev renewed successfully (expires 2026-10-09)",
    read: true,
    timestamp: "2026-07-10T14:20:00Z",
    priority: "low",
  },
  {
    id: "n7",
    type: "system",
    title: "Storage warning",
    message: "PostgreSQL data store at 60% capacity (1.2TB / 2.0TB)",
    read: true,
    timestamp: "2026-07-10T12:00:00Z",
    priority: "high",
  },
  {
    id: "n8",
    type: "mail",
    title: "Spam filter update",
    message: "Spam rules updated: 2,847 messages blocked in the last 24 hours",
    read: true,
    timestamp: "2026-07-10T11:00:00Z",
    priority: "low",
  },
  {
    id: "n9",
    type: "admin",
    title: "User quota warning",
    message: "alice@mail.dev has reached 85% of their storage quota",
    read: true,
    timestamp: "2026-07-10T10:00:00Z",
    priority: "normal",
  },
  {
    id: "n10",
    type: "security",
    title: "Failed login attempts",
    message:
      "12 failed login attempts detected in the last hour from various IPs",
    read: true,
    timestamp: "2026-07-10T09:00:00Z",
    priority: "high",
  },
  {
    id: "n11",
    type: "system",
    title: "Weekly health report available",
    message: "System health report for Week 28, 2026 is ready to view",
    read: true,
    timestamp: "2026-07-10T08:00:00Z",
    priority: "low",
  },
  {
    id: "n12",
    type: "admin",
    title: "Group updated",
    message: "Engineering group membership updated: 3 members added",
    read: true,
    timestamp: "2026-07-09T16:00:00Z",
    priority: "low",
  },
];
